require('basic')
require('plugins')
require('theme')
require('keybindings')
require('plugins-config/nvim-tree')
require('plugins-config/bufferline')
require('plugins-config/lualine')
require('plugins-config/telescope')
require('plugins-config/dashboard')
require('plugins-config/project')
require('plugins-config.nvim-treesitter')
-- lsp
require('lsp/setup')
require('lsp/cmp')
require('lsp/ui')
require('lsp.none-ls')
